import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navigation from "../components/navigation/navigation";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>FS Demo - Optimizely</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navigation/>
        </div>
    );
};

export default Home;
