import { Grid, Item } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Article from "../components/article/article";
import List from "../components/list/list";
import Navigation from "../components/navigation/navigation";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>FS Demo - Optimizely</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navigation />

            <Grid container padding={4} spacing={2}>
                <Grid item xs={8}>
                    <Article/>
                </Grid>
                <Grid item xs={4}>
                    <List/>
                </Grid>
            </Grid>
        </div>
    );
};

export default Home;
